<?php

namespace  Ftg\Sms\Facades;

use Illuminate\Support\Facades\Facade;

class Sms extends  Facade
{
    protected static function getFacadeAccessor()
    {
        return 'ftg-sms';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}